### ISSUE TITLE
add an --at option

### ISSUE THREAD

**Issue by scottleibrand** [loudnate/openaps-predict#27]
Would be nice to have an --at option to get just an instantaneous IOB reading as of a provided timestamp (likely usually from read_clock).

**Comment by loudnate** [comment]
Let's do `start_at` and `end_at`, since some folks would prefer to get the IOB decay but not the "false" history that records after the first history event.

**Comment by scottleibrand** [comment]
So does this mean that start_at and end_at need to be 5m apart to get one value returned?  Or will it always start at the start_at value, so providing the same time for both will get you an instantaneous IOB?

**Comment by loudnate** [comment]
The latter:

https://github.com/loudnate/openaps-predict/pull/33/files#diff-d54d7ac860faca6f0a464c5ddfdfcb59R1139

**Comment by loudnate** [comment]
```
$ openaps use predict walsh_iob normalize_history.json --settings read_settings.json --start-at read_clock.json --end-at read_clock.json 
[
  {
    "date": "2015-12-06T21:00:02", 
    "amount": 2.6983543984003964, 
    "unit": "U"
  }
]
```
